team: db-team
role: db
service: postgres-db
ansible_connection: aws_ssm
ansible_region: "eu-central-1"
ansible_aws_ssm_bucket_name: "ansible-ssm-bucket-oleg"
postgres_exporter_version: "0.15.0"
postgres_exporter_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
